# Generated by Django 5.1.2 on 2024-10-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_result_keywordresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
