# Generated by Django 5.1.2 on 2024-10-30 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_keyword_scheduled_time_alter_keyword_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 12, 47, 38, 610720)),
        ),
    ]
