# Generated by Django 5.1.2 on 2024-10-30 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_keyword_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 14, 16, 17, 532752)),
        ),
    ]
