# Generated by Django 5.1.2 on 2024-11-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_keyword_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='status',
        ),
    ]
