# Generated by Django 5.1.2 on 2024-11-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_remove_keyword_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
